export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";

export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";

export const GET_DETAILS_FAIL = "GET_DETAILS_FAIL";

export const GET_RESET_DETAILS = "GET_RESET_DETAILS";
